#!/bin/sh

# Activate python virtual environment and start hacktrack

cd ${0%/*}  # go to directory where this script lives

. env/local/bin/activate  # activate python virtual environment

mkdir -p ~/tmp/
./hacktrack 2>~/tmp/hacktrack_errlog # run hacktrack window management tool

echo Sleeping 1 hour to let you see any exit messages...
sleep 3600
