#!/bin/sh

# Activate python virtual environment and start hacktrack

cd ${0%/*}  # go to directory where this script lives

mkdir -p ~/tmp/

while true; do
    env/bin/python3 hacktrack 2>~/tmp/hacktrack_errlog # run hacktrack window management tool
    echo "Hacktrack crashed, will run it again in 5 seconds"
    sleep 5
done
